export const COMMON_BUTTON_SIZE_CLASS = 'h-12 w-52';
export const COMMON_BUTTON_PADDING_CLASS = 'px-5 py-2';
export const COMMON_BUTTON_CLASS = `${COMMON_BUTTON_SIZE_CLASS} ${COMMON_BUTTON_PADDING_CLASS} rounded-md`;